### PR TITLE
Exit with nonzero status on build error

### LINKED ISSUE #184: Please exit with nonzero on failed builds
Like #94, but for real. `cli.ts` has:
```typescript
const build = debounce(async function build() {
  try {
    // do build
  } catch (e) {
    process.stderr.write(e.stack);
  }
});

build().catch(e => {
  console.error(e);
  process.exit(1);
});
```

so any exceptions are suppressed and the `catch` is never executed.

### PR DESCRIPTION
**Pull request by bakkot**
Fixes #184.

### CODE REVIEW

File: test/cli.js [hunk 1]
```diff
@@ -0,0 +1,16 @@
...
+const execSync = require('child_process').execSync;
+
+describe('ecmarkup#cli', () => {
+  it('exits cleanly on success', () => {
+    execSync('./bin/ecmarkup.js test/example.html', { encoding: 'utf8' });
+  });
+
+  it('exits with an error on error', () => {
+    assert.throws(() => {
+      execSync('./bin/ecmarkup.js test/malformed.bad.html', { encoding: 'utf8' });
```
Comment (ljharb) [inline test/cli.js]: lol does ecmarkup really write a ".bad.html" file on errors (－‸ლ)

Comment (bakkot) [reply test/cli.js]: No, that's a file I added for the purposes of this test.

Comment (ljharb) [reply test/cli.js]: ahhh ok cool :-)
